# Generated by Django 4.1 on 2025-05-01 11:22

import os
import uuid
from django.utils.text import slugify
from django.db import migrations, models


def movie_image_file_path(instance, filename):
    _, extension = os.path.splitext(filename)
    filename = f"{slugify(instance.title)}-{uuid.uuid4()}{extension}"
    return os.path.join("uploads/movies/", filename)


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=movie_image_file_path,
            ),
        ),
    ]
